### PR TITLE
Simpler UX/UI and simpler codebase

### PR DESCRIPTION
**Pull request by Fakamoto**
This implements a new simpler UI for claix, no Panels, just simple text, also using arrows selection for choices

### CODE REVIEW

**Comment by Fakamoto** [comment]
@wrabit please check when you can and improve if you see something that could be done better.

"Revise Command" action is to be implemented

**Comment by Fakamoto** [comment]
Not ready for merge as it is WIP

**Comment by wrabit** [comment]
@Fakamoto, I added enquirer as a dep

- https://github.com/Fakamoto/claix/commit/7fda072b7c1908a96c333ebd68bcea184eec0fc3 

image

**Comment by wrabit** [comment]
- First thing I notice is that there is no 'loading' state, so it hangs whilst it queries and then provides the answer some seconds later.
- Revise command not working (I think you can just paste the suggestion into a new line in the terminal
- I think the ui could be worked on, will send notes

**Comment by Fakamoto** [comment]
> * First thing I notice is that there is no 'loading' state, so it hangs whilst it queries and then provides the answer some seconds later.
> * Revise command not working (I think you can just paste the suggestion into a new line in the terminal
> * I think the ui could be worked on, will send notes


Added loading.
Added revise command and also a new explain command.
UI still needs retouch

**Comment by Fakamoto** [comment]
Ended up using this branch not only for UI but actually a full refactor. Using much better STATE architecture to handle the different steps.

And added function calling, OS information for the assistant, etc.

**Comment by Fakamoto** [comment]
@wrabit if you can check the branch, and improve the UI if you know how to, that would be great, I want to merge this branch soon. Not much more to do on my side.

**Pull request merged**
